const tagvalues = {
  items: [
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2197097,
      name: "javascript",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1766523,
      name: "java",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1691273,
      name: "python",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1472549,
      name: "c#",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1398597,
      name: "php",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1330991,
      name: "android",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1063361,
      name: "html",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1010211,
      name: "jquery",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 719503,
      name: "c++",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 712508,
      name: "css",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 653805,
      name: "ios",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 622027,
      name: "mysql",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 585432,
      name: "sql",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 396260,
      name: "r",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 381313,
      name: "node.js",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 362412,
      name: "asp.net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 360250,
      name: "arrays",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 355595,
      name: "c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 325201,
      name: "ruby-on-rails",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 315638,
      name: "json",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 306966,
      name: ".net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 302360,
      name: "sql-server",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 295254,
      name: "reactjs",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 293397,
      name: "swift",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 291562,
      name: "objective-c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 279856,
      name: "python-3.x",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 263058,
      name: "django",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 262171,
      name: "angularjs",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 250161,
      name: "angular",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 243832,
      name: "excel",
    },
  ],
  has_more: true,
  quota_max: 10000,
  quota_remaining: 9995,
};

module.exports = tagvalues;
